import{a as v,i as n,S as m}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const L="44093100-ac5392341c86f6f111ffa7b1f",w="https://pixabay.com/api/";async function y(t,r=1,a=15){const s=`${w}?key=${L}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{return(await v.get(s)).data}catch{throw new Error("Failed to fetch images")}}function p(t){const r=document.querySelector(".gallery"),a=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:i,views:g,comments:h,downloads:b})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${s}" alt="${o}" loading="lazy">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${i}</p>
          <p class="info-item"><b>Views</b> ${g}</p>
          <p class="info-item"><b>Comments</b> ${h}</p>
          <p class="info-item"><b>Downloads</b> ${b}</p>
        </div>
      </div>
    `).join("");r.insertAdjacentHTML("beforeend",a)}function q(){const t=document.querySelector(".gallery");t.innerHTML=""}const $=document.querySelector("form");document.querySelector(".gallery");const c=document.querySelector(".loader"),d=document.querySelector(".load-more");let l="",u=1;const f=15;$.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements.searchQuery.value.trim(),!l){n.error({title:"Error",message:"Please enter a search query"});return}u=1,q(),c.classList.add("visible"),d.style.display="none";try{const r=await y(l,u,f);if(r.hits.length===0){n.warning({title:"No Results",message:"No images found. Try a different query."});return}p(r.hits),new m(".gallery a",{captionsData:"alt",captionDelay:250}),r.hits.length===f&&(d.style.display="block")}catch(r){n.error({title:"Error",message:r.message})}finally{c.classList.remove("visible")}});d.addEventListener("click",async()=>{u+=1,c.classList.add("visible");try{const t=await y(l,u,f);p(t.hits),new m(".gallery a",{captionsData:"alt",captionDelay:250}),t.hits.length<f&&(d.style.display="none",n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})),window.scrollBy({top:document.querySelector(".gallery").lastElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}catch(t){n.error({title:"Error",message:t.message})}finally{c.classList.remove("visible")}});
//# sourceMappingURL=commonHelpers.js.map
