import{a as v,i as n,S as L}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const q="44093100-ac5392341c86f6f111ffa7b1f",w="https://pixabay.com/api/";async function y(t,r=1,i=15){const o=`${w}?key=${q}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${i}`;try{return(await v.get(o)).data}catch{throw new Error("Failed to fetch images")}}function p(t){const r=document.querySelector(".gallery"),i=t.map(({webformatURL:o,largeImageURL:e,tags:s,likes:a,views:g,comments:h,downloads:b})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${o}" alt="${s}" loading="lazy">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${a}</p>
          <p class="info-item"><b>Views</b> ${g}</p>
          <p class="info-item"><b>Comments</b> ${h}</p>
          <p class="info-item"><b>Downloads</b> ${b}</p>
        </div>
      </div>
    `).join("");r.insertAdjacentHTML("beforeend",i)}function $(){const t=document.querySelector(".gallery");t.innerHTML=""}const E=document.querySelector("form");document.querySelector(".gallery");const d=document.querySelector(".loader"),u=document.querySelector(".load-more");let c="",f=1;const m=15;let l;E.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.target.elements.searchQuery.value.trim(),!c){n.error({title:"Error",message:"Please enter a search query"});return}f=1,$(),d.classList.add("visible"),u.style.display="none";try{const r=await y(c,f,m);if(r.hits.length===0){n.warning({title:"No Results",message:"No images found. Try a different query."});return}p(r.hits),l?l.refresh():l=new L(".gallery a",{captionsData:"alt",captionDelay:250}),r.hits.length===m&&(u.style.display="block")}catch(r){n.error({title:"Error",message:r.message})}finally{d.classList.remove("visible")}});u.addEventListener("click",async()=>{f+=1,d.classList.add("visible");try{const t=await y(c,f,m);p(t.hits),l&&l.refresh(),t.hits.length<m&&(u.style.display="none",n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})),window.scrollBy({top:document.querySelector(".gallery").lastElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}catch(t){n.error({title:"Error",message:t.message})}finally{d.classList.remove("visible")}});
//# sourceMappingURL=commonHelpers.js.map
